### ISSUE TITLE
feature request: watch .env file

### ISSUE THREAD

**Issue by obedm503** [mrsteele/dotenv-webpack#104]
this is a really cool plugin, but it's missing a huge feature for me. when I update the .env file, `webpack-dev-server` doesn't trigger a recompilation and the environment variables in the source code don't update.

for example, while developing a client side app I might have a local server and a cloud server, and I might change which server is used depending on which data I want to display
```env
# local server
API=localhost:8080/api/
# cloud server
# API=https://example.com/api/
```
changes
```env
# local server
# API=localhost:8080/api/
# cloud server
API=https://example.com/api/
```
is this possible?

**Comment by mrsteele** [comment]
Hey @obedm503 and thanks for the compliments.

The feature you are requesting is outside of the scope of this plugin, however I was able to find one for you: https://www.npmjs.com/package/filewatcher-webpack-plugin

Let me know if that solves your problem.

**Comment by obedm503** [comment]
it watches the file, but since no file imports `.env` as a dependency, the project doesn't recompile. optimally, this plugin would add `.env` as a dependency of any file that uses the environment variables. I think this would take care of the watching, recompiling and reapplying the `DefinePlugin`. 

even I I manually add `.env` as a `fileDependency` to the webpack `compiler` the plugin won't be reapplied and the `process.env.*` references won't be updated

**Comment by mrsteele** [comment]
I'm going to close this for the time-being as I believe this is outside the scope and responsibility of this plugin, but feel free to reopen if you disagree.
