### ISSUE TITLE
Support Webpack 4?

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [mrsteele/dotenv-webpack#113]
`npm WARN dotenv-webpack@1.5.4 requires a peer of webpack@^1 || ^2 || ^3 but none is installed. You must install peer dependencies yourself.`

**Comment by mrsteele** [comment]
@Iuriy-Budnikov Funny, I added this a little while back but I guess it was never officially released.

https://github.com/mrsteele/dotenv-webpack/blob/master/package.json#L42

v1.5.5 should be available in a minute to have this included. try and update to that version in a minute. If it still does not work please reopen.

Thank you for brining this to my attention.

**Comment by duduindo** [comment]
@mrsteele Thank!

**Comment by mrsteele** [comment]
Wow it looks like something happened with semantic release and it isn’t updating right (that’s not good).

I’m reopening this, but mainly because semantic release isn’t running (which probably explains why the original fix never went in).

I’ll repair that within the hour for you guys.

**Comment by duduindo** [comment]
@mrsteele You will create tag 1.5.6?

**Comment by mrsteele** [comment]
@duduindo looks like `1.5.5` is now in. Feel free to test and let me know if that worked.

**Comment by duduindo** [comment]
@mrsteele Version 1.5.5 don't  work with gulp and webpack 4.0.1.

#### Version 1.5.5 and Webpack 4.0.1:
```js
// gulpfile.js
const dotenv = require('dotenv-webpack');
```
```json
// package.json 
{
 "devDependencies": {
    "dotenv-webpack": "^1.5.5",
    "gulp": "^3.9.1",
    "webpack": "^4.0.1"
  } 
}
```
```bash
// Terminal
// Fail 

➜  project-test git:(develop) ✗ gulp
[SyntaxError: Unexpected token ...]
```

#### Version 1.5.5 and Webpack 3.11.0:
```bash
// Terminal
// Success

➜  project-test git:(develop) ✗ gulp
Using gulpfile /local/test-gulp-2/gulpfile.js
Task 'default' is not in your gulpfile
Please check the documentation for proper gulpfile formatting
```

**Comment by duduindo** [comment]
@mrsteele Please disregard my last comment. 

My version Node is 5.12.0. With Node >= 6 it worked.
Sorry.

**Comment by mrsteele** [comment]
@duduindo awesome!

What about you Iuriy-Budnikov, is Webpack 4 working for you?

**Comment by Iuriy-Budnikov** [comment]
Hey guys, I'll check today a bit later

**Comment by Iuriy-Budnikov** [comment]
Hey @mrsteele, works fine for me!

**Comment by mrsteele** [comment]
Thanks so much for catching that! Exposed a really annoying bug with my auto-deploys and wouldn't have found it had you guys not brought this to my attention.
