### ISSUE TITLE
Cannot setup for dotenv on test env

### ISSUE THREAD

**Issue by a-barbieri** [mrsteele/dotenv-webpack#119]
I'm using Jest to test my app (which is built upon this [boilerplate](https://github.com/ReactJSResources/react-webpack-babel)). I set up dotenv-webpack and works great on development and production, but I cannot set it up correctly to work on tests. Is there any different setup I'm not aware of? Shouldn't it be working out-of-the-box?

**Comment by mrsteele** [comment]
It should be working just fine. Would you mind showing me your webpack config and where you have your .env file located?

**Comment by a-barbieri** [comment]
`.env` file is in the root path.
I updated [this file](https://github.com/ReactJSResources/react-webpack-babel/blob/master/webpack.config.js) adding:

```javascript
```

**Comment by mrsteele** [comment]
Try removing this `DefinePlugin` located here: https://github.com/ReactJSResources/react-webpack-babel/blob/master/webpack.production.config.js#L34

**Comment by a-barbieri** [comment]
I tried to remove it but nothing happened. 
You can reproduce the issue this way:
1) clone the repo I set up
```
git clone https://github.com/a-barbieri/react-webpack-babel && cd react-webpack-babel && npm i  
```
2) run server
```
yarn run dev
```
You should see `dotenv-webpack should output a variable --> foo` on `localhost:8888`.
3) stop server `CMD+C` and run tests:
```
yarn run test
```
You should see 
```
console.log src/__tests__/app.test.jsx:10
    undefined
```

Point 2 outputs `process.env.FOO` on development environment: [see code](https://github.com/a-barbieri/react-webpack-babel/blob/master/src/__tests__/app.test.jsx#L10)
Point 3 outputs `process.env.FOO` (`undefined`) on test environment: [see code](https://github.com/a-barbieri/react-webpack-babel/blob/master/src/app.jsx#L13)

**Comment by mrsteele** [comment]
Okay, this is my theory:

Jest is not including your webpack config. Due to this you do not have access to your `.env` variables.

Solution:

At the top of your app.test.jsx file put `require('dotenv').config()`.

That should load in your `.env` variables in the context of node.

> KEEP IN MIND: The `dotenv-webpack` plugin simply adds your env variables to your bundled file. So if you have a server or test running you would need to run dotenv separately.

**Comment by a-barbieri** [comment]
It does load `.env` variables. Cool.
It doesn't give priority to `.env.test`though, but I set it inside `config`.

```javascript
// my-script.test.js
require('dotenv').config({ path: './.env.test' })
```

This way I can add `.env.test` to my repo and test it anywhere with fake global variables.

**Comment by mrsteele** [comment]
@a-barbieri glad I could help! Let me know if there is anything else I can help with.

**Comment by luckyyang** [comment]
jest.config.js
```
module.exports = {
  setupFilesAfterEnv: ['./jest.setup.js'],
```

jest.setup.js
```
require('dotenv').config({
  path: './.env',
});
```

.env
```
RPC_ENDPOINT=http://xxx.xxx.xxx.xxx
MODE=DEV
```
