### ISSUE TITLE
Can loaded variables be used in webpack.config itself?

### ISSUE THREAD

**Issue by DanielCardonaRojas** [mrsteele/dotenv-webpack#122]
Is there any way to do this ?

**Comment by mrsteele** [comment]
Hey @DanielCardonaRojas, I'm not sure I understand your request. Could you maybe explain it a little more or show me an example of what you mean?

**Comment by jethrogb** [comment]
Looking for this exact functionality right now

**Comment by jethrogb** [comment]
I guess you just have to do `require('dotenv').config();`

**Comment by mrsteele** [comment]
Oh, if you are just saying can I share the env variables node-side, yes you just do what @jethrogb suggested.

**Comment by DanielCardonaRojas** [comment]
Actually I figured it out. The down side is all variables are prefixed with 'proccess.env' and had to do JSON.parse to remove double quotes.: 

```javascript
module.exports = function(env) {
  let dotenv =  new Dotenv();
  let variables = dotenv.definitions;
  JSON.parse(variables['process.env.API_VERSION']);
  ...
}
```

**Comment by mrsteele** [comment]
@DanielCardonaRojas While that does work, that is not the recommended approach.

Instead, you can load your `.env` variables as follows:

```js
require('dotenv').config()

console.log(process.env.API_VERSION)
```

I'm going to close your issue has been solved and a proposed resolution has been presented. Let me know if this is not accurate and I will be happy to reopen and reevaluate.

**Comment by cgpro** [comment]
And the answer ;-)

You have to install dotenv separately. Then in your webpack.config.js place the following line at the very top (in my case the .env is in src):
```js
require('dotenv').config({ path: './src/.env' });
```

You can debug the right path with the following code:
```js
const nodeEnv = require('dotenv').config({ path: './src/.env' });
console.log(nodeEnv)
process.exit()
```
