### ISSUE TITLE
for multiple .env files

### ISSUE THREAD

**Issue by DarwinniwraD** [mrsteele/dotenv-webpack#124]
I added  a **_.env.development_** file, and config it in webpack config file like this
```
new Dotenv({
    path: path.resolve(__dirname, `../.env.${process.env.NODE_ENV}`),
})
```
the **_.env.development_** file was loaded success, but I  only get the **process.env.NODE_ENV** in my environmental variable 
what's wrong with that configuration, Thank you!

**Comment by mrsteele** [comment]
hey @DarwinniwraD, thanks for bringing this to my attention.

It would be really hard for me to know exactly what is wrong if I don't have more context...

I imagine your `.env.development` file is definitely populated with other envs and that your config doesn't overwrite this somewhere else?

**Comment by DarwinniwraD** [comment]
@mrsteele you're right, I found it, it was overwrite by
```
new webpack.DefinePlugin({
    'process.env': env
}),
```
thank you! 👍 👍
