### ISSUE TITLE
1.5.6 introduces a breaking change, shouldn't have been a patch release

### ISSUE THREAD

**Issue by modosc** [mrsteele/dotenv-webpack#129]
`dotenv@6.0.0` drops support for `node 6`:

https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md

**Comment by mrsteele** [comment]
@modosc darn greenkeeper... yeah sorry about that.

I have pinned the version to `v5.0.1` and `dotenv-webpack@v1.5.7` should be releasing soon with the fix.

https://github.com/mrsteele/dotenv-webpack/commit/705396a6f5d641a6dc195739876412e23316bc0a

If it doesn't look like it worked in the next ~5 minutes, let me know and I can see what went wrong.

Thanks @modosc for bringing this to my attention.
