### ISSUE TITLE
Allow empty vars in safe mode

### ISSUE THREAD

**Issue by mkrause** [mrsteele/dotenv-webpack#133]
In #14, empty variables were allowed, but only in non-safe mode. But even in safe mode we'd often like to use an empty string as a possible value. Can we make a distinction between `.env` variables that are not specified as opposed to variables that are just empty?

```
# .env.example
FOO=default
BAR=default
```

```
# .env
FOO=
```

The lack of `BAR` should result in an error, `FOO` should not.

Also worth noting that [dotenv-safe](https://www.npmjs.com/package/dotenv-safe) allows empty values, configurable through an "allowEmptyValues" option.

**Comment by mrsteele** [comment]
Hmmmm, Yeah if dotenv-safe supports that we should probably too, but I think it should be configurable just like dotenv. Any chance you wanna make a go at it?

**Comment by mkrause** [comment]
Sure! I just submitted PR #134. I've added an option `allowEmptyValues` (default false), similar to dotenv-safe.

**Comment by mkrause** [comment]
@mrsteele Do you think you'll have time to review?

**Comment by nusson** [comment]
Any update on this ?

**Comment by marcofugaro** [comment]
Is this repo dead? This feature is actually useful

**Comment by mrsteele** [comment]
Anyone willing to resolve the conflicts?

**Comment by marcofugaro** [comment]
If @mkrause is not available, I am willing to make a new PR with the old one's content.

**Comment by mkrause** [comment]
I can fix the conflicts. Over the weekend maybe.

**Comment by mkrause** [comment]
Updated the PR
