### ISSUE TITLE
Allow empty env vars

### ISSUE THREAD

**Issue by k-funk** [mrsteele/dotenv-webpack#14]
Getting this error: `Error: Missing environment variable: CDN_HOST`

**webpack.config.js**

    ...
      new DotenvPlugin({
        safe: false,
        systemvars: false
      })
    ...

**.env**

    CDN_HOST=
    OTHER_KEY1=ABC123

I know that I can just delete that empty key to make it work, but I'd rather dotenv-webpack just dump the vars in without any validation.

**Comment by mrsteele** [comment]
Thanks for bringing this up. Let me test and see if I can reproduce / fix.

**Comment by mrsteele** [comment]
Alright, definitely can reproduce let me do a little digging.

**Comment by mrsteele** [comment]
1.2.1 is released to solve this problem.

Thank you @k-funk for bringing this to my attention. Let me know if you find anything else!

**Comment by k-funk** [comment]
Thanks for the super quick fix!
