### ISSUE TITLE
Commenting syntax?

### ISSUE THREAD

**Issue by binarybaba** [mrsteele/dotenv-webpack#144]
Hi,
may sound like a dumb question but does the standard javascript syntax follows here
or is it bash like syntax when adding comments?

**Comment by mrsteele** [comment]
This package follows the `dotenv` package, which uses the following syntax: https://github.com/motdotla/dotenv/blob/master/tests/.env#L13

I'll close this for now, but let me know if I didn't answer your question.

**Comment by binarybaba** [comment]
Ah thank you so much
