### ISSUE TITLE
Destructuring Blows Up

### ISSUE THREAD

**Issue by larron** [mrsteele/dotenv-webpack#147]
Defining variables in this way blows up and complains about the variable `process`

```
const {
  NODE_ENV: nodeEnv,
  DEBUG: debugStr,
  PORT: port,
  APP_URL: appUrl,
  API_URL: apiUrl,
  AUTH0_DOMAIN: auth0Domain,
  AUTH0_CLIENT_ID: auth0ClientId,
  AUTH0_AUDIENCE: auth0Audience,
  CROWDSALE_API_URL: crowdsaleApiUrl,
  TOKEN_ADDRESS: tokenAddress,
  PURCHASE_ADDRESS: purchaseAddress,
  SENTRY_DSN: sentryDsn
} = process.env
```

The current fix is to repetively define `process.env` for each variable.

**Comment by mrsteele** [comment]
Man if I had a dime....

This is a bigger problem than you might have expected. In doing extensive research on the matter (https://github.com/mrsteele/dotenv-webpack/issues/70#issuecomment-316720414), we have found that it just isn't possible to have webpack bundle your envs securely, while also supporting destructuring.

I wish it were possible as I am a huge destructure fan, but with the way we want only used envs packaged it wouldn't be feasible to support both approaches without compromising security.

I'm going to close this as a duplicate, but feel free to have a conversation over there if you wish.
