### ISSUE TITLE
dotenv-webpack doesn't read the .env variables at all

### ISSUE THREAD

**Issue by eugene-zheng0208** [mrsteele/dotenv-webpack#149]
"react": "^16.2.0",
"dotenv-webpack": "^1.5.7",
"webpack": "^3.10.0",

Webpack configuration
```
plugins: [
		new ExtractTextPlugin("bundle.css"),
		new OpenBrowserPlugin({ url: 'http://localhost:3000' }),
		new Dotenv({
      path: path.resolve(__dirname, './.env'), // Path to .env file (this is the default)
      systemvars: true,
    })
	],
```

.env file is at the root level of the project

```
componentDidMount() {
		console.log(process.env);
	}
```

I got an empty object, so funny
Of course, I already read all issues, articles and even did the same as examples, but can't figure out.

**Comment by mrsteele** [comment]
Hey @eugene-zheng0208 and thanks for reaching out.

If you have a normal webpack environment (where your `.env` file is in your app root, and `webpack.config.js` is a sibling file), you can probably remove the `path` property like so:

```json
{
  plugins: [{
    new Dotenv({
      systemvars: true // this allows you to read from the system's preinstalled process.env
    })
  }]
}
```

Let me know if that works for you.

**Comment by eugene-zheng0208** [comment]
Dear @mrsteele 
I tried so, but no luck
while I could get system vars...

**Comment by nvma** [comment]
@mrsteele my apologies for hijacking the issue, my question is only partially related

```
const Dotenv = require('dotenv-webpack');

module.exports = {s
  ...
  plugins: [
    new Dotenv(),
    new HtmlWebPackPlugin({myVar: process.env.VAR_FROM_DOTENV})
  ]
  ...
};
```

Do I get access to env variables in the webpack config file itself?

**Comment by mrsteele** [comment]
@nvma If you need access to system vars in your config, do the following:
```js
require('dotenv').config()
module.exports = {s
  ...
  plugins: [
    new Dotenv(),
    new HtmlWebPackPlugin({myVar: process.env.VAR_FROM_DOTENV})
  ]
  ...
};

```

The `dotenv` plugin is loaded as a dependency to mine.

**Comment by mrsteele** [comment]
@eugene-zheng0208 If you have access to system vars, but are not getting your `.env` file loading, that means its not finding your file.

Maybe you can explain your file setup and running webpack configuration so I can be more aware of where everything is in your application.

**Comment by darkhorse-dev** [comment]
Dear @mrsteele , thank you for your timely response

![image](https://user-images.githubusercontent.com/30766060/46741364-b542a700-cc59-11e8-9efe-ccb59f13e2fb.png)

![image](https://user-images.githubusercontent.com/30766060/46741473-f1760780-cc59-11e8-93a1-961c0a21a7ed.png)

**Comment by nvma** [comment]
@mrsteele Thanks, works like a charm. Very useful plugin!

**Comment by mrsteele** [comment]
Great to hear!

I'm closing this for the time being but let me know if there is anything else I can do for you.
