### ISSUE TITLE
Don't bundle .env file

### ISSUE THREAD

**Issue by pgbastante** [mrsteele/dotenv-webpack#154]
Hi,

I'm wondering if I can do this with this plugin. I want to keep the .env file as an independent file I can modify in my bundle, but I don't see any way to do it. The reason I want to do that is because we have a lot of production environments (one for each client hosted on our servers) and I want to create only one artifact (to store it in nexus) but keep the .env file out of the bundle so I can modify it on each one with the specific parameters of each environment.

Thank you and sorry if this is not in the scope of the plugin.

**Comment by mrsteele** [comment]
We currently do not bundle your env file. If you mean with your package, I would suggest you look at gitignore rules, otherwise I think that is out of the scope of this plugin as all we focus on is providing env variables to the scope of your webpack files.

I'll close this for now but let me know if there is something I misunderstood and feel free to reopen.

**Comment by pgbastante** [comment]
No, it's the bundle what I'm looking for. In my dist folder after the build is completed, the env variables are part of the files in the dist folder, I don't have a .env file in my dist folder I can modify (thats what I'm looking for).

Is there any plan to do that as an option or I have to look for another solution?

Thank you very much fot your quick response.

**Comment by mrsteele** [comment]
I would say that’s out of scope of this project. Maybe a web pack copy file module or a post build script that copies the file is what you may be looking for.

Matt Steele

On Dec 5, 2018, at 4:58 PM, Pablo García Bastante <notifications@github.com<mailto:notifications@github.com>> wrote:


No, it's the bundle what I'm looking for. In my dist folder after the build is completed, the env variables are part of the files in the dist folder, I don't have a .env file in my dist folder I can modify (thats what I'm looking for).

Is there any plan to do that as an option or I have to look for another solution?

Thank you very much fot your quick response.
