### ISSUE TITLE
Troubles working with @babel/preset-env useBuiltIns

### ISSUE THREAD

**Issue by kilgarenone** [mrsteele/dotenv-webpack#172]
`process.env` is turning up empty in my code, and I have narrowed it down to some configs in my babel-preset-env. It looks like this:

```
const configureBabelLoader = (browserList = []) => {
  return {
    test: /\.(ts|js)x?$/,
    exclude: /node_modules/
    use: {
      loader: "babel-loader",
      options: {
        cacheDirectory: true,
        presets: [
          [
            "@babel/preset-env",
            {
              exclude: ["transform-regenerator", "transform-async-to-generator"],
              modules: false
              // corejs: 3,
              // useBuiltIns: "usage",
              // targets: {
              //   browsers: browserList
              // }
            }
          ],
          ["@babel/preset-typescript", { jsxPragma: "h" }]
        ],
        plugins: [
          [
            "@babel/plugin-transform-react-jsx",
            {
              pragma: "h"
            }
          ],
          "@babel/proposal-class-properties",
          "@babel/proposal-object-rest-spread",
          "@babel/plugin-syntax-dynamic-import",
          "module:fasst-async"
        ]
      }
    }
  };
};
```

For some reason, everything is fine if I don't do this: 
```
 corejs: 3,
 useBuiltIns: "usage",
 targets: {
    browsers: browserList
 }
```

**Comment by mrsteele** [comment]
If you have a build step that happens BEFORE you call webpack build, it could definitely interfere.

This plugin runs when you call "build" so if you don't have access to your `.env` file when you call `webpack build`, you will have problems.

Looking at your configs, you have a lot of complexity. Unfortunately I wont be able to help you as its a problem with your application, not this plugin.

For the time-being I'm going to close this, but if you can narrow it down a lot more so its just this plugin and your application we can definitely take a look.
