### ISSUE TITLE
How to prevent duplicate environment variable settings.

### ISSUE THREAD

**Issue by kmkzt** [mrsteele/dotenv-webpack#176]
If I accidentally set duplicate environment variables in one environment file, it will be broken. Can I prevent errors or warnings by displaying them?

**Comment by mrsteele** [comment]
I think it will by default not set if it already is. So you just need to remove the duplicate.

**Comment by kmkzt** [comment]
@mrsteele 

Thank you for your response.

I would like to add an option to display an error if there are duplicate environment variables, if there is no feature to check duplicates.

```js
New Dotenv ({
  duplicate: 'warning', // warning or error, or false, default is false
})
```

It is possible to prevent application corruption by overriding environment variables that add this feature.
