### ISSUE TITLE
[Question] is require('dotenv').config reliable? 

### ISSUE THREAD

**Issue by mustafawm** [mrsteele/dotenv-webpack#186]
Hello

I came across #122 & #165 about accessing env vars in webpack.config.js  and the recommended approach was to:

```js
// webpack.config.js
const envVars = require('dotenv').config({ path: 'path/to/.env' }).parsed;

module.exports = {
// ...
    devServer: { 
        proxy: {
          '/api': envVars.API_URL,
        },
    }
}
```

The question: is this a reliable API? 

If yes, can we add a section **Use in webpack.config.js** to the docs? 
>I think many people will find it useful..

**Comment by mrsteele** [comment]
I think your question is directly related to `dotenv` plugin, not this one (which utilizes that one).

But to answer your question, you only need to call `require('dotenv').config({ path: 'path/to/.env' })` and then reference with `process.env.API_URL`. It will be globally scoped in the node process that is running.

Closing for now as I don't think it directly applies here but feel free to reopen.
