### ISSUE TITLE
Any way to have dotenv-webpack work with obfuscator loader?

### ISSUE THREAD

**Issue by ninze** [mrsteele/dotenv-webpack#188]
Seems like dotenv-webpack doesn't work with [obfuscator-loader](https://www.npmjs.com/package/obfuscator-loader). Apparently the code is obfuscated before dotenv vars are replaced. Any way to have this solved? This would be an incredibly useful feature.

**Comment by mrsteele** [comment]
What happens when you use them together? I'd be curious what exactly breaks as this plugin simply uses `webpack.DefinePlugin` under the hood.

**Comment by ninze** [comment]
Difficult to say exactly, as obfuscator-loader obfuscates things :) But I get `Undefined is not an object`, which probably refers to `process.env`. 

I think it has to do with the feature described as **"variables that are explicitly referenced in your code"**. After obfuscator-loader does its job, the vars are probably no longer "explicitly referenced".

**Comment by mrsteele** [comment]
Are you using `enforce: 'post'` to make sure it loads last? I imagine it has already been obfuscated and that is why your variables are not being properly replaced.

**Comment by ninze** [comment]
I wasn't using that option, however adding it didn't make any difference.

Here is my js-related webpack config part:

		noParse: /\.min\.js/,

		rules: [
			{
				enforce: 'post',
				test: /\.secret\.js$/,
				exclude: /(node_modules|vendor|samples)/,
				use: {
					loader: 'obfuscator-loader',
					options: {
						deadCodeInjection: true,
						deadCodeInjectionThreshold: 0.4,
						identifierNamesGenerator: 'mangled',
						rotateStringArray: true,
						stringArray: true,
						stringArrayEncoding: 'base64',
						stringArrayThreshold: 0.75,
						transformObjectKeys: true,
					},
				},
			},
			{
				test: /\.js$/,
				exclude: /(node_modules|vendor|samples)/,
				use: {
					loader: 'babel-loader',
					options: {
						cacheDirectory: true,
					},
				},
			},
        ......

**Comment by NullScope** [comment]
I have the same issue with the same obfuscator loader and config, is there a fix or workaround?

**Comment by ninze** [comment]
My workaround was to only obfuscate some code and make sure I don't use ENV vars in the files that I want obfuscated. Basically I name the source files `*.secret.js` where I want obfuscation, the rest of the code is processed by traditional webpack setup, which doesn't conflict with dotenv plugin.

**Comment by mrsteele** [comment]
@ninze may be on to something. It’s strange that I use this on one of my sites with no problems and this has come up. Behind the scenes we are just using webpack.DefinePlugin and it’s not anything too fancy that I imagine wouldn’t play well with this..

**Comment by NullScope** [comment]
From my testing it seems it works in development, but as soon as I build (using electron + reactjs) it will no longer work, I made a repo [here](https://github.com/NullScope/dotenv-webpack-javascript-obfuscator-issue) with a sample project made with electron forge typescript webpack template and added `ReactJS`, `dotenv-webpack` and `javascript-obfuscator` with default settings to reproduce the issue, without any modifications, if you run `npm start` you will see that it will print out the process environment variables just fine, but if you run `npm run make squirrel` and run the exe from `out/my-new-app-win32-x64`, you will see that it will no longer print the print the process environment variables

**Comment by NullScope** [comment]
I just did some more testing, it seems my usage of `dotenv` in the webpack modules dirtied the process enviroment in development, making the obfuscator-load always run will also cause the same issue on `npm start`, I've updated the repo for this.

**Comment by NullScope** [comment]
So I think I understand what is happening,`obfuscator-loader` is being called before `dotenv-webpack` meaning this plugin cannot find the `process.env` calls, so my "fix" right now was taking the source code of this plugin and transforming into a custom loader and use it on my rules file, I added a branch to the same repo called `dotenv-webpack-loader`

**Comment by mrsteele** [comment]
I had mentioned above that yoou have to use `enforce: 'post'` to make sure it runs last. Have you tried that @NullScope ?

https://github.com/mrsteele/dotenv-webpack/issues/188#issuecomment-561188205

**Comment by NullScope** [comment]
@mrsteele Yes, you can check the example repo on `webpack.rules.js` that `enforce: 'post` is being set on `obfuscator-loader`

**Comment by mrsteele** [comment]
@NullScope I'm closing this. You are using a deprecated module. Try using a module that is supported with the current versions of Webpack and DefinePlugin.

https://github.com/javascript-obfuscator/obfuscator-loader#this-package-is-deprecated

If you still run into problems, I would suggest asking that author, as this package is pretty bare-bones and is only using two dependencies (dotenv and webpack).

**Comment by NullScope** [comment]
The author deprecated the module two days ago, so at the time of commenting on this issue it was still valid, either way, I converted your plugin into a webpack rule and it works flawlessly so that is what I've been using

**Comment by DK013** [comment]
> The author deprecated the module two days ago, so at the time of commenting on this issue it was still valid, either way, I converted your plugin into a webpack rule and it works flawlessly so that is what I've been using

Hi, I'm experiencing the same issue here so can I please have a link to your loader? thanks.
