### ISSUE TITLE
Defaults override systemvars with safe option

### ISSUE THREAD

**Issue by kascakm** [mrsteele/dotenv-webpack#193]
Hi,

I have following plugin configuration:
```
new DotenvPlugin({
            defaults: true,
            safe: true,
            systemvars: true
        })
```

on a CI build I don't have a .env file, so I'm passing all required vars as
`VAR1=FROM_SYSTEMVAR npx webpack ...`

In the project I have
.env.defaults:
```
VAR1=FROM_DEFAULTS
```

.env.example:
```
VAR1=
```

I would expect process.env.VAR1 to contain FROM_SYSTEMVAR, but it gives me FROM_DEFAULTS

I suspect that https://github.com/mrsteele/dotenv-webpack/blob/13a3e120eb86b26d8bdb8e39ecf5531100c82561/src/index.js#L67
```
// add the leftovers
    if (safe) {
      Object.assign(vars, env)
    }
```

does not actually adds leftovers but overrides systemvars.

I would appreciate if you could explain if this is expected behaviour.

Thanks
Michal

**Comment by marcofugaro** [comment]
Yeah I also have this issue, it's very common to have:

```js
// .env or .env.defaults

API_KEY=d9a87s6gdyiuas9d78abs9n8d0
```

```js
// .env.example

API_KEY=
```

Then using the variables a a systemvar in the CI.

Actually #180 would solve this, @mrsteele would you mind merging that PR?

**Comment by joaonsantos** [comment]
I also had this issue overriding my specified .env file with `defaults=false`.

So defaults is overriding everything regardless of `defaults`.

**Comment by tobias-trozowski** [comment]
as https://github.com/mrsteele/dotenv-webpack/pull/274 was merged this issue should be solved.

**Comment by mrsteele** [comment]
Closing, Awesome thanks!
