### ISSUE TITLE
Request - Option to throw when 'env' file not found

### ISSUE THREAD

**Issue by alonrbar** [mrsteele/dotenv-webpack#195]
Hi,

I'm using the plugin like so:

```javascript
new Dotenv({ path: './path-to-my-env-file/my.env' })
```

I renamed the file (say `./path-to-my-env-file/my2.env`) and ran webpack but unfortunately the build process completed successfully. This is problematic since the actual application does not work because it lacks some of it's configuration. 

I would really appreciate it if there'd be a `required` flag of some sort that will throw an error at build time if the env file is not found. I'll be happy to create a PR for that if it will help.

Thanks

**Comment by tjcampbell** [comment]
@alonrbar you can use the `safe` option to check against an example .env file. That way if the file isn't found it will throw as the required env vars won't be present.

**Comment by alonrbar** [comment]
@tjcampbell Thanks, but that means I'll have to maintain a duplicate env file for each configuration I'm supporting (I have multiple env files each with another set of variables in it) and that's not quite what I'm looking for.

**Comment by mrsteele** [comment]
An alternative option would be to use `defaults` so you can set things that should always be set, otherwise `safe` would be your only other option. Feel free to reopen if you think this doesn't resolve your use-case.

**Comment by alonrbar** [comment]
@mrsteele thank you for your response. 

I feel that this does not quite solve my issue as I described in my previous comment but I understand that this may be only relevant to me and few other users. Hopefully I'll have the time to PR sometime in the future so you'll be able to examine my proposal (unfortunately I can't address that any time soon).

Thanks again!
