### ISSUE TITLE
Substitution breaks when assigning to variable in code

### ISSUE THREAD

**Issue by nathanlepori** [mrsteele/dotenv-webpack#214]
I have the following code in my Node application:
```
if (!process.env.API_TOKEN_ALGORITHM ||
    !['HS256', 'HS384', 'HS512', 'RS256', 'RS384', 'RS512', 'ES256', 'ES384', 'ES512', 'PS256', 'PS384', 'PS512']
        .includes(process.env.API_TOKEN_ALGORITHM)) {
    logger.warn('Invalid algorithm provided. Falling back to RS512.')
    process.env.API_TOKEN_ALGORITHM = 'RS512';
}
```

After bundling with webpack and running the bundle i get the following error:
```
undefined:39
    "RS512" = 'RS512';
    ^^^^^^^

SyntaxError: Invalid left-hand side in assignment
```

The plugin is wrongly replacing the left side of the expression. I'm wondering if there could be a fix for that or is it a limitation of the plugin.

**Comment by mrsteele** [comment]
Yeah, I suggest that if you need to do that asignment you either pull it above before you call webpack's config, or do the following:
```js
let API_TOKEN_ALGORITHM = 'RS512'
if (process.env.API_TOKEN_ALGORITHM &&
    ['HS256', 'HS384', 'HS512', 'RS256', 'RS384', 'RS512', 'ES256', 'ES384', 'ES512', 'PS256', 'PS384', 'PS512']
        .includes(process.env.API_TOKEN_ALGORITHM)) {
    API_TOKEN_ALGORITHM = 'RS512';
} 

// only use the locally-referenced version now.
console.log(API_TOKEN_ALGORITHM)
```

**Comment by mrsteele** [comment]
Closing due to lack of participation and cannot reproduce.

Feel free to reopen this if you can provide more details, thanks.

**Comment by nathanlepori** [comment]
Sorry I forgot to close it. The suggested solution works. Thanks
