### ISSUE TITLE
[next.js] plugin reassignment error

### ISSUE THREAD

**Issue by SeoHyunDeock** [mrsteele/dotenv-webpack#221]
I'm using serverless framework with nextjs and using ".env".

So, I did install "dotenv-webpack" plugin and apply to webpack config in next.config.js.

I have two cases.

[first]
```
	webpack: config => {

                ....

		config.plugins.push(new Dotenv({ path: path.resolve(__dirname, envPath) }));

                ...

		return config;
	},
```

[second]
```
	webpack: config => {

                ....

                config.plugins = config.plugins || [];
  
                config.plugins = [
                    ...config.plugins,
                    new Dotenv({ path: path.resolve(__dirname, envPath) })
                ];

                ...

		return config;
	},
```

First case is working properly but, second is not.

what difference two cases?

Thank you.

**Comment by mrsteele** [comment]
I believe nextjs loads your env for you by default, so you shouldn't need my plugin unless you are using an older version.

If you are using an older version, I think you need this.

But at the end of the day, I think your problem might be with NextJS, and specifically what spreading is doing to the plugins references. I imagine you break references.

Closing for now and you are welcome to ask them.
