### ISSUE TITLE
Fails if variable is not defined or .env file is missing

### ISSUE THREAD

**Issue by tysonmatanich** [mrsteele/dotenv-webpack#229]
Everything works fine if the variables are defined in my .env file, however if the .env file is missing or a particular variable is missing then in get the follow error:

```
ReferenceError: process is not defined
```
I even tried using the .env.defaults file to make sure all variables are defined, but still no luck.

```
config.plugins.push(new Dotenv({ path: "./.env", defaults: true }));
```

Using dotenv-webpack version 2.0.0

**Comment by mrsteele** [comment]
The error smells suspect to the fact that you may be running webpack in a strange way. `process` should exist if it is running in the context of node.

Any additional details on how you are running this might help me understand your problem better.

**Comment by tysonmatanich** [comment]
I investigated this further and I think I figured out what is happening for when `process.env` is undefined.

The Dotenv constructor returns something like the following object. This works great when using these defined variables such as `process.env.TEST_1`, however when you try to use something not defined like `process.env.TEST_3` you get an exception.

```js
{
  definitions: {
    'process.env.TEST_1': '"one"',
    'process.env.TEST_2': '"two"'
  }
}
```

However, if the Dotenv constructor instead returned it with a `process.env` object wrapping the variables then it would also catch any environment variables that aren't defined but were attempted to be used. I'm sure lots of projects are relying on the existing functionality so perhaps this could live behind a property flag (`new Dotenv({ allowUndefined: true })`).

```js
{
  definitions: {
    'process.env': {
      TEST_1: '"one"',
      TEST_2: '"two"'
    }
  }
}
```

I ran into the issue in a Preact project and added the following line to my preact.config.js to work around the issue.

```js
config.plugins.push(
    new DefinePlugin({
      "process.env": {},
    })
  );
```

The defaults seem to load fine for me now so I must have fat fingered something there.

**Comment by mrsteele** [comment]
@tysonmatanich That is not happening to me. Locally I tested using my `dotenv-webpack-example` repo and added a ref to an env that doesn't exist.

# the code
![1](https://user-images.githubusercontent.com/5257284/91350600-eaf0ca80-e7b4-11ea-97c9-1a6d1e2811a9.PNG)

# the console
![2](https://user-images.githubusercontent.com/5257284/91350604-ec21f780-e7b4-11ea-9398-40b895c3dae0.PNG)

# the env
![3](https://user-images.githubusercontent.com/5257284/91350609-ed532480-e7b4-11ea-88bc-0cf621f7cbd6.PNG)

**Comment by tysonmatanich** [comment]
I ran your example project and got the same result. It must be something Preact or one of its dependencies is doing under the covers. Glad there is an easy work around I can use. Thanks for investigating and hope this can help others if they run into the same issue.
