### ISSUE TITLE
3.0.0 breaks compatibility with next.js

### ISSUE THREAD

**Issue by EvHaus** [mrsteele/dotenv-webpack#238]
I use the `next` framework. After upgrading this plugin from v2.0.0 to 3.0.0 it's failing to render its basic view with this error:

```
Error was not caught TypeError: Cannot use 'in' operator to search for 'electron' in undefined at next-dev.js:8
```

This is coming from `next` internal code which attempts to read a value from `process.versions`.

Is the `dotenv-webpack` plugin doing something weird with `process.versions` (and especially something different between 2.0.0 and 3.0.0) that could cause this behavior?

**Comment by ntamas** [comment]
Could this be related to #240?

**Comment by pfarrar1** [comment]
> I use the `next` framework. After upgrading this plugin from v2.0.0 to 3.0.0 it's failing to render its basic view with this error:
> 
> ```
> Error was not caught TypeError: Cannot use 'in' operator to search for 'electron' in undefined at next-dev.js:8
> ```
> 
> This is coming from `next` internal code which attempts to read a value from `process.versions`.
> 
> Is the `dotenv-webpack` plugin doing something weird with `process.versions` (and especially something different between 2.0.0 and 3.0.0) that could cause this behavior?

Able to reproduce this. If you bump back to v2.0.0 from v3.0.0

**Comment by pfarrar1** [comment]
@EvHaus @ntamas not sure if this helps.

I was experiencing the same error above. Creating a `.env.development` file using the advice here helped me (https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables). I removed my `dotenv-webpack` from package.json updated my next config and started to use the built-in env. 

I'm upgraded to version `next@9.5.5` and this worked for me. 

<img width="258" alt=".env.development file" src="https://user-images.githubusercontent.com/500743/95696777-224ef580-0c02-11eb-9203-3e1a12b1889c.png">

**Comment by mrsteele** [comment]
Sorry about this, I had to rollback the support for webpack@5 for the moment. Try upgrading to v4 and see if that resolves your issues.

**Comment by EvHaus** [comment]
Thanks. 4.0.0 fixed the issue for me.
