### ISSUE TITLE
3.0.0 causes an issue with Terser / Terser Webpack plugin

### ISSUE THREAD

**Issue by u01jmg3** [mrsteele/dotenv-webpack#239]
https://github.com/mrsteele/dotenv-webpack/blob/7749894d0398f2f92300fa26666b60dd49e66abb/src/index.js#L143-L145

[Line 144](https://github.com/mrsteele/dotenv-webpack/commit/7749894d0398f2f92300fa26666b60dd49e66abb#diff-1fdf421c05c1140f6d71444ea2b27638R144) causes [Terser](https://github.com/terser/terser) to error out with `Unexpected token: punc (:)`

Is there anyway to accomplish this differently?

---

No choice but to stick with `v2` for now

**Comment by Enase** [comment]
also brakes `serverless-env-generator` and many others

**Comment by riboher** [comment]
Also breaking cypress tests due to the same unexpected token.
`> Unexpected token ':'`

Going back to v2.0.0 fixes the issue

**Comment by sebastianpikand** [comment]
Stumbled upon the same issue and man did it take some time to figure out where the problem was coming from.

RE: https://github.com/webpack-contrib/terser-webpack-plugin/issues/326

**Comment by ntamas** [comment]
This issue is probably another manifestation of #240 (or vice versa).

**Comment by charlesyclim** [comment]
This happens to me also but is in the bluebird package. It corrupt the [Async.prototype.FatalError function](https://npmdoc.github.io/node-npmdoc-bluebird/build/apidoc.html#apidoc.element.bluebird.async.prototype.fatalError). When it sees process.stderr.write(, it replace the "process" with something like {"env":{}}, so it becomes {"env":{}}.stderr.write(
Will be good if could exclude node_modules, as well as options to affect only filtered list of files.

**Comment by charlesyclim** [comment]
Realize this problem was because of v3 which is gues is not compatible with my webpack v3, i just need to install the older version, 2.0.0, and it works fine now. 
npm i -D dotenv-webpack@2.0.0

**Comment by mrsteele** [comment]
Sorry about this, I had to rollback the support for webpack@5 for the moment. Try upgrading to v4 and see if that resolves your issues.

**Comment by u01jmg3** [comment]
Closing as the issue with v3 has been resolved in v4 [by removing the problematic code]().

However, at some point Webpack 5 compatibility will need to be looked at again. Happy to help with testing when the time comes.

**Comment by mrsteele** [comment]
@u01jmg3 testing is good, but contributing is better ;)

**Comment by u01jmg3** [comment]
> _testing is good, but contributing is better ;)_

Erm... dare I say testing could have prevented v3 from being released and then breaking our code! 😝

**Comment by mrsteele** [comment]
All testing passed @u01jmg3, but looks like it didn't catch this bug specifically...

**Comment by u01jmg3** [comment]
I meant real world testing such as an alpha or beta release. Smaller footprint than releasing to everyone as production ready.

**Comment by mrsteele** [comment]
@u01jmg3 congratulations you're on my list ;)

**Comment by u01jmg3** [comment]
Sounds ominous but I'll take it that's a good thing :)
