### ISSUE TITLE
3.0.0 - setImmediate.js:80 Uncaught SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by asolopovas** [mrsteele/dotenv-webpack#243]
Hi I am having this problem when upgrading from  v1.7.0 to v3.0.0. 
https://stackoverflow.com/questions/64232479/vue-js-webpack-i-get-setimmediate-js80-uncaught-syntaxerror-unexpected-token/64242919#64242919

**Comment by sudosandwich3** [comment]
@asolopovas I am running into this same issue.  What was the resolution?

**Comment by asolopovas** [comment]
> @asolopovas I am running into this same issue. What was the resolution?

downgrade the package
