### ISSUE TITLE
Error in changelog text v6.0.0

### ISSUE THREAD

**Issue by NicolasBonduel** [mrsteele/dotenv-webpack#287]
Hi,

Quick feedback: I believe there is a mistake in your latest release changelog.
It says both `supporting webpack 5` and `dropping support for webpack 5`.

Looking at the commits, I think you meant `dropping support for node 9`.

Thanks for your work!

**Comment by mrsteele** [comment]
Resolved! Thanks for bringing this to my attention. I use semantic-release and we were bouncing around there with webpack 5 support (still feel like we are). I'll close this as its addressed. Thanks again!
