### ISSUE TITLE
Not working with webpack.DefinePlugin

### ISSUE THREAD

**Issue by lucasbento** [mrsteele/dotenv-webpack#30]
Hey there!

The plugin is not working with `webpack.DefinePlugin`, dotenv-webpack was listed after it and was not loading any environment vars.

I tried a few things (also `systemvars` which does not seem to get the vars from `DefinePlugin`) **what worked was putting dotenv-webpack call before `webpack.DefinePlugin`**.

`webpack.DefinePlugin` is needed so webpack does not need to do any checks for the `NODE_ENV` environment and reduces the bundle size (a lot).

I guess there should be a way to get the `DefinePlugin` vars on dotenv-webpack.

**Comment by mrsteele** [comment]
Just to make sure I understand, you have something similar to:

```javascript
// webpack.config.js
const Dotenv = require('dotenv-webpack');
const { DefinePlugin } = require('webpack'); 

module.exports = {
  ...
  plugins: [
    new DefinePlugin({
        // ...
    }),
    new Dotenv({
      path: './.my.env', // if not simply .env
      safe: true // lets load the .env.example file as well
    })
  ]
  ...
};
```

**Comment by lucasbento** [comment]
Yes, sorry I didn't include any examples, something like this:

```javascript
new webpack.DefinePlugin({
  'process.env': {
    NODE_ENV: '"production"'
  }
}),
new dotEnv({
    path: './env',
    safe: './env',
}),
```

I use the same path for `safe` and `path` because I don't use a `.env.example` file.

**Comment by mrsteele** [comment]
Feel free to simply remove the `safe` param. This would remove the safety checks since you just want to use the variables provided by your `.env` file.

**Comment by mrsteele** [comment]
Okay, looking at your example, i'm betting the following is happening:

If you look at this line:

https://github.com/mrsteele/dotenv-webpack/blob/master/src/index.js#L51

You will see I am assigning a variable like you on `process.env`.

Since you just have the one, have you tried changing your DefinePlugin to use?:

```javascript
new webpack.DefinePlugin({
  'process.env.NODE_ENV': "production"
}),
new dotEnv({
  path: './env',
  safe: './env',
}),
```

This should help in the definition phase.

**Comment by mrsteele** [comment]
Although that wouldn't explain why it all worked as expected when you did one before the other... Are you sure it all worked when you changed the order?

**Comment by lucasbento** [comment]
I'm gonna try what you just said, that does make sense.

Yes, it is running on production already. :)

**Comment by lucasbento** [comment]
@mrsteele: it works in the way that you just said.

I guess `webpack.DefinePlugin` has an incremental way of defining new env vars.

**Comment by mrsteele** [comment]
Yeah, sorry about the issues but if anything maybe a good idea to open an issue with the `DefinePlugin` with webpack.

**Comment by lucasbento** [comment]
alright, cool, thank you @mrsteele!
