### ISSUE TITLE
Can I alias-wrap environment variables?

### ISSUE THREAD

**Issue by GalGreenfield** [mrsteele/dotenv-webpack#305]
Hello,

Right now to have aliased environment variables I use `webpack.DefinePlugin()`:
```javascript
new webpack.DefinePlugin({
    'CONFIG': {
        'prefix': JSON.stringify(process.env.prefix),
        'auth_token': JSON.stringify(process.env.auth_token)
    }
})
```

Which then I can access later with `CONFIG.suffix` and `CONFIG.auth_token`.

Is it possible to use this library (`dotenv-webpack`) to alias the .env file so I can call `CONFIG.<env-var>` as above?

**Comment by mrsteele** [comment]
You can... but you would have to string some things together. I would recommend just using `dotenv` directly in your config if you don't intend to use this plugin for bundle-specific references.

Closing this, thanks for the question.
