### ISSUE TITLE
Document `definitions` property on plugin instance

### ISSUE THREAD

**Issue by comatory** [mrsteele/dotenv-webpack#310]
My webpack configuration passes dotenv file info to HTML template. This means that I want to use the plugin to load the config and then access the parsed values which I do like this (example):

```javascript
    const dotEnv = new DotEnvWebpack()

   // [...]
    new webpack.DefinePlugin({
      'process.env.SOME_DATA':
        dotEnv.definitions['process.env.SOME_DATA'],
    }),
    // [...]
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, 'src', 'templates', 'index.ejs'),
      templateParameters: {
        data: dotEnv.definitions['process.env.SOME_DATA'']
      },
      favicon: path.resolve(__dirname, 'static', 'favicon.ico'),
    }),
```

This property is accessible yet not documented in the plugin API. I'd assume that

- the naming should be such to follow naming convention of private JS properties, e.g.: `dotEnv.definitions → dotEnv._definitions` to make it more clear it should not be used directly
- if the property can and should be accessible, document it and provide mechanism for getting values, e.g. getter method: `dotEnv.getValue('SOME_DATA')`

If anyone uses webpack configs written in typescript and also uses `@types/dotenv-webpack`, I have created a patch that can be injected with [patch-package](https://www.npmjs.com/search?q=patch-package):

```git
diff --git a/node_modules/@types/dotenv-webpack/index.d.ts b/node_modules/@types/dotenv-webpack/index.d.ts
index e8c166c..b8c1714 100644
--- a/node_modules/@types/dotenv-webpack/index.d.ts
+++ b/node_modules/@types/dotenv-webpack/index.d.ts
@@ -14,6 +14,7 @@ import { Compiler, WebpackPluginInstance } from 'webpack';
 declare class DotenvWebpackPlugin implements WebpackPluginInstance {
     constructor(options?: DotenvWebpackPlugin.Options);
     apply(compiler: Compiler): void;
+    definitions: Record<string, string>;
 }
 
 declare namespace DotenvWebpackPlugin {
```

However I'd just like to know how to use the plugin in such a way that would allow me getting data from the instance.

**Comment by mrsteele** [comment]
You are making things a little harder for you, I would say either use this plugin as documented:
```js
new DotenvWebpack(),
```

...or just use `dotenv`
```js
require('dotenv').config()

new webpack.DefinePlugin({
  'process.env.whatever': JSON.stringify(process.env.whatever)
})
```

I'll close this as I believe this is what's going on, but feel free to reopen if you still need help.

**Comment by comatory** [comment]
I see what you mean. My aim was to have just one dependency that reads env files and since I could accomodate this plugin, I thought why not.

But you are right, I'm probably better of with regular `dotenv`.
