### ISSUE TITLE
v7 checklist

### ISSUE THREAD

**Issue by mrsteele** [mrsteele/dotenv-webpack#363]
A few things I want to consolidate for the next version break:
- [x] Drop support for Node 8 (jest cannot run on node 8 and comes with some security issues).
- [x] Either add an [ignoreStub](https://github.com/mrsteele/dotenv-webpack/pull/289) flag or [automatically read config](https://github.com/mrsteele/dotenv-webpack/pull/360) to determine when to stub. (closes #271)

Anything else I'm missing?

**Comment by BeeeQueue** [comment]
- Drop support for Webpack versions under 4
- Remove deprecated options
