### ISSUE TITLE
Error when a env var is not created using systemvars

### ISSUE THREAD

**Issue by raphaklaus** [mrsteele/dotenv-webpack#37]
Hello, I realized that if I have not set a environment variable in my system and in my webpack config I setup dotenv-webpack to get systemvars, and use this variable in my JavaScript the rendering goes crazy, it simply put the whole env without parsing anything.

**Comment by mrsteele** [comment]
I can look at this but seems odd the test for this would pass just fine unless it is specific to a new webpack thing.

What version of `webpack` and `dotenv-webpack` are you using and what is your exact config for `dotenv-webpack`?

**Comment by raphaklaus** [comment]
webpack: 1.13.3
dotenv-webpack: 1.3.1

config:

```javascript
new dotEnv({
  path: './.env',
  systemvars: true
}),
```

More information: In this repository I use system env vars, and the .env file doesn't exists.

**Comment by mrsteele** [comment]
I was able to reproduce locally. I have a fix in place and I will let you know when that is shipped.

**Comment by mrsteele** [comment]
@raphaklaus `1.4.2` has now been released resolving this bug. Thanks for notifying me!
