### ISSUE TITLE
Additional README information

### ISSUE THREAD

**Issue by j-feng13** [mrsteele/dotenv-webpack#39]
I tried this library recently while trying to load some environment variables into a React + Webpack application. 
There is no documentation on this, but the plugin is essentially a wrapper for dotenv and Webpack's DefinePlugin, which does a text replace on all instances of ```process.env``` in the resulting bundle. 
On the client side, this means that all ```process.env.NODE_ENV === 'production'``` checks that React does get rewritten to ```{SECRETS}.NODE_ENV```. This leaks secrets to the client side.

On the server side, this breaks code modifying ```process.env``` because all ```process.env``` calls are rewritten to ```{SECRETS}```. 

I can open a PR to update the README if you would like.

**Comment by mrsteele** [comment]
Would PR #36 solve this? I have been meaning to get back to the author about feeling it unneeded, but if you guys think this would help I wouldn't mind adding it.

I have history with using `dotenv` so it is strait forward for me.

**Comment by j-feng13** [comment]
I think it would be nice to be more explicit with how it works under the hood. There are some definite 'gotchas' with this library. Using the ```DefinePlugin``` means that ```'process.env'``` is literally being replaced in all instances. This can have a big impact on React applications that rely on Webpack for bundling because React uses a lot of ```process.env.NODE_ENV``` checks. 

I can write something up over the weekend that explains it clearly.

I ended up using the preload functionality from ```dotenv``` for my server side and ```DefinePlugin``` directly on the client side to control what is being passed in. I wouldn't have known about the gotchas without checking on the resulting Webpack bundle and reading into the code of this library.

**Comment by mrsteele** [comment]
Okay, yeah @j-feng13 that would be excellent.

You can use the following as a DRAFT:

```markdown
### Usage

Behind the scenes we use LINK TO DOTENV. Essentially you create a `.env` file in your project root and add variables:

``
MY_VAR=whatever
``

The variables can then be accessed in your code with the following:

``javascript
console.log(process.env.MY_VAR);
// outputs: whatever
``

> RECOMMENDED: Add `.env` to your `.gitignore` file to not leak information.
```

**Comment by fakiolinho** [comment]
Great work but it is important to mention that `webpack.DefinePlugin()` is returned under the hood. I 've just discovered your package and i lost 5 mins while my own `DefinePlugin` declaration was in place and then i checked under the hood and decided to drop it. Now it works like a charm.

**Comment by fakiolinho** [comment]
In order to omit some critical .env vars which you don't want to include in the final bundle, you can pass an array of exceptions:

```javascript
// In webpack.config.js
new Dotenv({
    path: resolve(__dirname, '../.env'),
    systemvars: true,
    exceptions: ['DB_USER', 'DB_PASS']
}),

// In dist/index.js code
constructor (options) {
    options = Object.assign({
        path: './.env',
        safe: false,
        systemvars: false,
        exceptions: []
    }, options)
...
}

const env = _.omit(this.loadFile(options.path), [...options.exceptions]);
```

**Comment by j-feng13** [comment]
Thanks for the suggestions, @fakiolinho.
I might also suggest having separate ```.env``` files: one for your client and one for the server.
It may be easier to keep track of what information you have for the client vs server. 
@mrsteele Sorry I didn't get to the write up over the weekend. I'll do it tonight.
