### ISSUE TITLE
Use dotenv-safe

### ISSUE THREAD

**Issue by lucasbento** [mrsteele/dotenv-webpack#4]
Use [dotenv-safe](https://github.com/rolodato/dotenv-safe) instead of dotenv.

**Comment by mrsteele** [comment]
Thanks for the recommendation!

I saw someone else had created something similar to it, but for our workflow we don't really use it.

If you want, you can use `webpack-dotenv-plugin` which does just that: https://www.npmjs.com/package/webpack-dotenv-plugin

I don't think our packages are much different apart from that.

**Comment by lucasbento** [comment]
@mrsteele yeah, tried that one and did not work.

Anyway, thank you for yours!

**Comment by mrsteele** [comment]
Didn't work really?

Did mine work? 😆

**Comment by mrsteele** [comment]
I ask because if his is having problems, maybe I can look into incorporating dotenv-safe as an optional alternative:

```javascript
const Dotenv = require('dotenv-webpack');

module.exports = {
  ...
  plugins: [
    new Dotenv({
      safe: true
    })
  ]
  ...
};
```

**Comment by lucasbento** [comment]
@mrsteele I would not star it if it did not work haha 😆 

All the other options that I tried failed with something similar to this issue: https://github.com/request/request/issues/1529

That way you mentioned would be great.

**Comment by mrsteele** [comment]
If you wanna guiny-pig this, I just did a feature branch to support this.

Options:
* path (String) - The path to the env (defaults to `./.env`
* sample (String) - The path to the sample env (defaults to `./.env.example`
* safe (Bool) - If you want it to be on safe-mode (defaults to `false`)

The branch is `feature/dotenv-safe`. Let me know if that works like you want. Seems like a good addition.

**Comment by lucasbento** [comment]
@mrsteele awesome!

If I stall from your branch it throws this error:
![image](https://cloud.githubusercontent.com/assets/6207220/17411662/90302614-5a4f-11e6-8480-5d84e792c3ca.png)

Do you know why?

It installs normally if I use the published package on npm.

**Comment by mrsteele** [comment]
You probably need to `npm i` from the dir in `node_modules`.

```
cd ./node_modules/dotenv-webpack
npm i
```

**Comment by mrsteele** [comment]
Might have to `npm run build` too to make sure you have the dist version if you are not running as es6.

**Comment by lucasbento** [comment]
@mrsteele I will try it as soon as I get home.

**Comment by lucasbento** [comment]
```bash
npm i git+https://github.com/mrsteele/dotenv-webpack.git#feature/dotenv-safe -D
cd node_modules/dotenv-webpack
npm i && npm run build
```
Throws an error because `./src` folder does not get pulled, so I tried cloning everything than switching to the feature branch which throws the same error that we experienced yesterday.

**Comment by mrsteele** [comment]
Well if you clone you would still need to build if your environment doesn't support Babel things.

1. Clone
2. npm i 
3. npm run build

That way you have all the dependencies, as well as access to the dist version of the plugin.

Matt Steele

**Comment by mrsteele** [comment]
Okay I finally have time to tackle this a bit.

Just realized something a little problematic with this. You have access to the dotenv but not the actual env variables of the machine.

Going to look into refactoring all of this in a little bit and i'll touch base when that is all done.

**Comment by lucasbento** [comment]
Ok, cool.

**Comment by mrsteele** [comment]
I got it all checked in and it is releasing as `v1.1.0` as part of the CI release schedule.

Please check this specific version out and if you have any problems, please open a bug ticket.

Have a look at the new README.md file which displays the supported additional params to satisfy this need.

Thanks for the suggestion and all the help along the way!
