### ISSUE TITLE
Hot reload dotenv files

### ISSUE THREAD

**Issue by PezCoder** [mrsteele/dotenv-webpack#425]
#### What?

I love how easy it is to include this plugin to inject these dot env values in the bundle like so:
```
new DotEnv({ path: envPath[0] }),
```

We use these env files to point to a particular API endpoint, which makes it really easy to test things out.

My question is, is there a way to make sure the bundle refreshes when a respective env file changes. To be able to change these env values on the fly would be great, without the pain of restarting webpack everytime a user changes an env.

More like how loaders like `style-loader` do it for CSS automatically?

I'm not sure if this may be a webpack specific question than to do with the package specifically, but I appreciate any help on this one.

Possible related issue: https://github.com/mrsteele/dotenv-webpack/issues/92

**Comment by PezCoder** [comment]
We use `create-react-app` & have mostly ejected it, which internally uses `webpack.HotModuleReplacementPlugin` for JS specific bundles.

**Comment by mrsteele** [comment]
Very possible, but really depends on your setup. You would need to watch your env files as part of your webpack config and force reloading when that happens. Of course it is a build-time operation so making sure to rebuild your bundles would be key.

**Comment by PezCoder** [comment]
@mrsteele That's good to know. Will, you able to please point me to the right documentation?

I explored webpack's documentation but couldn't figure out a way to achieve this.

**Comment by mrsteele** [comment]
Yeah, looks like watching in general only looks at imported files (which this plugin doesn't do).

Maybe try this one: https://www.npmjs.com/package/webpack-watch-files-plugin

**Comment by PezCoder** [comment]
Crazy, thankss !
