### ISSUE TITLE
how to setup .env & .env.production - multiple host

### ISSUE THREAD

**Issue by cullsin** [mrsteele/dotenv-webpack#434]
Hello, 

I am using webpack server to boot my react application. Can anyone suggest how to define multple .env environment. It should pick .env for development and .env.production for production mode.

Thanks,
Raja K

**Comment by mrsteele** [comment]
Maybe...
```js
new Dotenv({
  path: process.env.NODE_ENV === "production" ? "./production.env" : "./development.env"
})
```

Something like that?

**Comment by njekpang** [comment]
This also works if you don't want to worry about redefining all env variables in .env.production. You can simply define the variables that are different in production.
```js
new Dotenv({
  path: process.env.NODE_ENV === 'production' ? '.env.production' : '.env',
  defaults: '.env',
}),
```

**Comment by mrsteele** [comment]
Awesome! Sounds like you have options. I’ll close this for now, but let me know if this didn’t work.

**Comment by lucassarcanjo** [comment]
Hey, just contributing with my solution to the same problem. Because my webpack.config.js is not in the root folder, I needed to use path resolution:

```js
new Dotenv({
            path:
                process.env.NODE_ENV === "development"
                    ? path.resolve(__dirname, "../.env.development")
                    : path.resolve(__dirname, "../.env"),
            systemvars: true,
        }),
```
