### ISSUE TITLE
TypeError: Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by WhereJuly** [mrsteele/dotenv-webpack#449]
I use `dotenv-webpack` under Vue CLI v4 presumably with Webpack 5. 

When I run the CLI I get the error `TypeError: Cannot read property 'target' of undefined` in `node_modules\dotenv-webpack\dist\index.js:64:62`.

The line that throws the error is
``` javascript
var target = (_compiler$options$tar = compiler.options.target) !== null && _compiler$options$tar !== void 0 ? _compiler$options$tar : 'web';
```
as the `compiler` object does not have `options` member (and looks somehow odd). 

If I hardcode `var target = 'web';` and run the CLI again the next exception that comes is `TypeError: Cannot read property 'tap' of undefined` and it comes from `node_modules\webpack\lib\DefinePlugin.js:97:30`.

This looks like a systemic problem. 

Is there any hint to understand how to fix this issue? Any direction to think about?

**Comment by mrsteele** [comment]
Interesting, I have a simple fix to conditionally check for that option, but I kinda want to research it a bit more to see if that is the "webpack" way to do it.

**Comment by mrsteele** [comment]
For kicks, can you replace that line of code in your `node_modules` folder with the following?

```js
      var target = (_compiler$options$tar = (_compiler$options = compiler.options) === null || _compiler$options === void 0 ? void 0 : _compiler$options.target) !== null && _compiler$options$tar !== void 0 ? _compiler$options$tar : 'web';

```

**Comment by WhereJuly** [comment]
@mrsteele Hello. 

> For kicks, can you replace that line of code

I did. It brings another exception `ReferenceError: _compiler$options is not defined` on the replaced line number.

What is interesting is that it throws the exception on the later created Vue CLI project (say at the time I created this issue) but it does not throw on the older Vue CLI project (created many monts ago).

FWIW at the same time the local webpack version is v.4.46.0 on both and the global one is v5.46.0. As well I made an `npm update` on the project that throws but it did not change the situation.

For the experiment sake I have just created the basic clean Vue CLI project with Vue 2 Default setup, added `dotenv-webpack` and the exception is in place. You could try to repeat this or I could archive and send you the actual project for your experimentation if you have time.

BTW let me know if any opportunity to donate to the package or you directly. The package is pretty handy and I use it in commercial projects so would like to contribute like this.

**Comment by mrsteele** [comment]
@WhereJuly Yeah I'd love it if you had that vanilla broken version somewhere for me to experiment on just to see.

**Comment by WhereJuly** [comment]
@mrsteele Great. Here you are the zipped project as is https://drive.google.com/file/d/1wFvCgTauw7CiYZKWj745qKk7ro_Ml2w9/view?usp=sharing

**Comment by mrsteele** [comment]
Two comments:
1. You can also just make a repo instead of an entirely zipped file. No need to make me manually download all your dependencies and its easier to spot problems.
2. Right off the bat nothing works. Even removing this plugin so I'm not sure how much this plugin is your problem. But I also see you didn't put the `plugins` property in the right spot. It should be on the root, and you nested it in resolve in `vue.config.js`

```js
configureWebpack: {
        devServer: {
            host: 'localhost'
        },
        // don't nest it, just leave it in the root webpack config
        // resolve: {
            plugins: [
                new Dotenv()
            ]
        // }
    }
```

But even fixing that, I'm getting numerous errors elsewhere. I'm going to close this for now but I think there is more going on here than just misconfigured webpack and I don't have any other reports about this.

**Comment by WhereJuly** [comment]
@mrsteele Thanks for investigating. Actually the fix was to move the plugin instantiation out of `resolve` key and directly into `plugins` key as you suggested above. Sorry for making the hassle and thanks a lot again.
