### ISSUE TITLE
dotenv-webpack doesn't substitute within dependencies in React 16

### ISSUE THREAD

**Issue by jmfrees** [mrsteele/dotenv-webpack#455]
# The issue

I have a project in which I use environment variables like `process.env.REACT_APP_VARNAME`. `dotenv-webpack` correctly substitutes these occurrences. However, I have some external code that is shared between a few of my projects. These components are installed via NPM. Occurrences of these same variables within these components are not substituted when I build my app in React 16. If I upgrade my app to use React 17, the variables are properly substituted throughout. I have yet to find any reason why this is. I would really like to be able to use environment variables in my r16 code.

# Expected behavior:

All `process.env.[varname]` occurrences should be substituted within first-party and second or third-party code.

# Actual behavior:

```console
Uncaught (in promise) TypeError: e is undefined
```
`process` is minified into some variable e, and `e.env.[variablename]` is `undefined`.

# Details

My `package.json`:
```json
{
  "name": "MyApp",
  "version": "1.1.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack",
    "build-production": "webpack --mode=production",
    "clean": "rm -f public/static/build/js/*"
  },
  "repository": {
    "type": "git",
    "url": "git@gitlab.com:MyApp.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/preset-env": "^7.14.4",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.6",
    "dotenv-webpack": "^7.0.3",
    "webpack": "^5.38.1",
    "webpack-cli": "^4.7.2"
  },
  "dependencies": {
    "@babel/plugin-transform-runtime": "^7.14.3",
    "moment": "^2.25.1",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.1",
    "react-components": "git+ssh://git@gitlab.com/mycustomcomponents.git#working",
    "react-dom": "^16.12.0",
    "react-infinite-scroll-component": "^5.0.4",
    "react-markdown": "^6.0.2",
    "react-router-bootstrap": "^0.25.0",
    "react-router-dom": "^5.1.2",
    "react-script": "^2.0.5",
    "react-scroll-up": "^1.3.3",
    "react-select": "^3.1.0",
    "three": "^0.129.0",
    "vanta": "^0.5.18"
  }
}
```

My `webpack.config.js`:
```js
const path = require("path");
const Dotenv = require("dotenv-webpack");

module.exports = {
  mode: "development", 

  entry: {
    "main-page": path.resolve(__dirname, "src/pages/MainPage.jsx"),
  },

  output: {
    filename: "[name].[contenthash].js",
    path: path.resolve(__dirname, "public/static/build/js"),
  },

  optimization: {
    moduleIds: "deterministic",
  },

  module: {
    rules: [
      {
        test: /\.m?jsx$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/preset-env", "@babel/preset-react"],
            plugins: ["@babel/plugin-transform-runtime"],
          },
        },
      },
      {
        test: /\.(png|jpe?g|gif)$/i,
        use: [
          {
            loader: "file-loader",
          },
        ],
      },
      {
        test: /\.css$/i,
        use: ["style-loader", "css-loader"],
      },
    ],
  },

  resolve: {
    alias: {
      Components: path.resolve(__dirname, "src/components"),
    },

    extensions: [".js", ".jsx"],
  },
  plugins: [
    new Dotenv({
      silent: true,
      systemvars: true,
    }),
  ],
};
```
```bash
❯ npm --version
7.17.0
```

**Comment by mrsteele** [comment]
Webpack from version 4 to 5 did this interesting thing where they stopped replacing undefined `process.env` values with `{}`.

If you have a variable `process.env.OOPS` that you thought you set, but forgot or was expecting it to be falsy or whatever  would have some funny code bundled looking like so `{}.OOPS`.

Some code was written a while back to account for this and add it back in, since Webpack took it out. As long as you are targeting to the web you should get that stub back. Can you try adding `target: "web"` to your webpack config and see if that resolves anything?
