### ISSUE TITLE
Add variable substitution

### ISSUE THREAD

**Issue by Bilge** [mrsteele/dotenv-webpack#463]
The following should be possible

```env
# .env
foo=bar
baz="$foo bat"
```

```js
# my.js
process.env.baz // "bar bat"
```

[Symfony's implementation of .env files](https://symfony.com/doc/current/configuration.html#configuring-environment-variables-in-env-files) takes this much further by supporting additional Bashisms such as [parameter expansion](https://wiki.bash-hackers.org/syntax/pe) (`${var:-default}`) and [command substitution](https://wiki.bash-hackers.org/syntax/expansion/cmdsubst) (`$(command)`). However, for an initial implementation, I would be happy with just simple variable substitution to compose subsequent env variables from previously defined env variables.

**Comment by mrsteele** [comment]
We do support the notion of "expanded" variables.

Did you read the [README](https://github.com/mrsteele/dotenv-webpack#properties)? Have you seen it defined in the [test-scenario](https://github.com/mrsteele/dotenv-webpack/blob/master/test/envs/.expanded#L13)?

I'm closing this, and suggest that in the future you look at documentation before opening an issue 😉

**Comment by Bilge** [comment]
Is it possible I did read the readme?

**Comment by mrsteele** [comment]
Just add “expand: true” and use the proper syntax. We use JS syntax instead of php syntax

**Comment by Bilge** [comment]
There is no *PHP syntax*, only *Bash syntax*, of which only a strictly limited subset is currently supported.
