### ISSUE TITLE
How to load var from package.json

### ISSUE THREAD

**Issue by jasan-s** [mrsteele/dotenv-webpack#464]
i.e 
    "start": "APP_ENV=dev webpack serve",

**Comment by mrsteele** [comment]
You need a node process defined first, perhaps you could create a script that loads your env first?
```js
// init.js
require('dotenv').config()
```

```json
// package.json
{
  ...
  "scripts": {
    "start": "node init && webpack server"
  }
}
```

Closing, but feel free to mention if that isn't correct.
