### ISSUE TITLE
Restrict to prefix like CRA does with REACT_APP_x

### ISSUE THREAD

**Issue by vjpr** [mrsteele/dotenv-webpack#473]
Allow specifying a prefix or a function to filter which are allowed.

**Comment by mrsteele** [comment]
I'd suggest one of two things:
1. A PR would be nice to see how this might play out in the configs, maybe help with a use-case too.
2. Perhaps you just take all your envs and spread them back out in `webpack.DefinePlugin` with the prefix. Delegate that responsibility for your specific use-case.

**Comment by mrsteele** [comment]
#482 actually resolves this. I’ll close but let me know if this wasn’t what you meant.
