### ISSUE TITLE
'process' is not defined.

### ISSUE THREAD

**Issue by alucardu** [mrsteele/dotenv-webpack#477]
I'm trying to use a environment variable in my React app:

```
const init = () => {
  console.log(process.env.NODE_ENV);
  ...
}
```

Returns the error:

> 'process' is not defined., var process: NodeJS.Process

I've created a `.env` file in the root (same as the webpack config file)

Packages:

```
    "dotenv-webpack": "^7.0.3",
    "eslint-webpack-plugin": "^3.0.1",
    "webpack": "^5.56.1",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.3.1"
    "ts-loader": "^9.2.6",
    "typescript": "^4.3.5"
    "eslint": "^7.32.0",
    "eslint-plugin-react": "^7.20.5",
    "react": "^17.0.2",
```

webpack:

```
const Dotenv = require('dotenv-webpack');

module.exports = {
  ...
  plugins: [
    new Dotenv(),
  ],
};
```

**Comment by alucardu** [comment]
Figured it perhaps was an ESLint issue, and not a dotenv-webpack issue:

https://stackoverflow.com/questions/50894000/eslint-process-is-not-defined 

```
"env": {
        "node": true,
        "commonjs": true,
        "browser": true,
        "es6": true
       }
```

adding `"node": true` fixed the issue.

**Comment by mrsteele** [comment]
Glad to hear @alucardu, I'll close the ticket
