### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by Alpsboy-Jin** [mrsteele/dotenv-webpack#479]
Hey, I decided to use dotenv-webpack for my API keys but I've been getting this error "process is not defined" and I can't seem to fix the issue.
When I console.log(process.env.NODE_ENV), development shows up on my console just fine but when I try to console.log(process.env.API_KEY), I get process is not defined.

**Below is my .env**
```
API_KEY=123
```

**Below is my package.json**
```
	"scripts": {
		"build": "webpack",
		"serve": "webpack serve"
	},
	"author": "Jin",
	"license": "ISC",
	"devDependencies": {
		"@babel/core": "^7.16.0",
		"@babel/preset-env": "^7.16.0",
		"@types/xml2js": "^0.4.9",
		"babel-loader": "^8.2.3",
		"clean-webpack-plugin": "^4.0.0",
		"css-loader": "^6.4.0",
		"dotenv-webpack": "^7.0.3",
		"eslint": "^8.2.0",
		"file-loader": "^6.2.0",
		"gh-pages": "^3.2.3",
		"html-loader": "^3.0.0",
		"html-webpack-plugin": "^5.5.0",
		"mini-css-extract-plugin": "^2.4.4",
		"style-loader": "^3.3.1",
		"svg-inline-loader": "^0.8.2",
		"url-loader": "^4.1.1",
		"webpack": "^5.63.0",
		"webpack-cli": "^4.9.1",
		"webpack-dev-server": "^4.3.1"
	},
	"dependencies": {
		"assert": "^2.0.0",
		"buffer": "^6.0.3",
		"stream": "0.0.2",
		"timers": "^0.1.1",
		"xml2js": "^0.4.23"
	}
```
**Below is my webpack.config.js**

```
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const Dotenv = require("dotenv-webpack");
const path = require("path");

module.exports = {
	mode: "development",
	entry: "./src/index.js",
	output: {
		filename: "main.js",
		path: path.resolve(__dirname, "dist"),
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: "./src/template.html",
		}),
		new CleanWebpackPlugin(),
		new MiniCssExtractPlugin({ filename: "[name].[contentHash].css" }),
		new Dotenv(),
	],
};

```
Just to add, my .env file is in the root directory

**Comment by kaocong** [comment]
i use in vuejs. i can use process in vue file, but ' process is not defined' in main.js
why...

**Comment by nbkhope** [comment]
It seems like webpack version 5 has removed some polyfills that might cause the issue. Read https://webpack.js.org/migrate/5/

Try the following workaround, specifying the property in your webpack configuration file:

```
resolve: {
  fallback: {
    process: false
  }
```

**Comment by mrsteele** [comment]
On Webpack 5 you have to target your webpack config. I believe `target: 'node'` should work if that is the environment you are targeting.

**Comment by Alpsboy-Jin** [comment]
> On Webpack 5 you have to target your webpack config. I believe `target: 'node'` should work if that is the environment you are targeting.

Wow, it was that simple to fix, thank you very much for your support! Works like a charm now 😁
