### ISSUE TITLE
Support import.meta.env as an alternative to process.env

### ISSUE THREAD

**Issue by niieani** [mrsteele/dotenv-webpack#480]
Would be nice if dotenv-webpack supported switching the prefix to import.meta.env instead of process.env, since that's more portable (process.env is node-specific, whereas `import.meta` is an es module standard). This will also make it more compatible with other bundlers, like vite's default [env](https://vitejs.dev/guide/env-and-mode.html) treatment.

**Comment by mrsteele** [comment]
This actually sounds like a pretty cool idea. Any interest in writing a PR?
```js
// default
new Dotenv({
  prefix: `process.env.`
})
// process.env.PORT

// your suggestion
new Dotenv({
  prefix: `import.meta.`
})
// import.meta.PORT

// scallable idea
new Dotenv({
  prefix: `MY_TEST_`
})
MY_TEST_PORT
```

**Comment by niieani** [comment]
Would love to help, but I can't commit to a making a PR at this time due to time constraints.

**Comment by mrsteele** [comment]
Since we merged in #482 this should be good, but feel free to reopen.

**Comment by dbwcooper** [comment]
Hi @niieani 

the `prefix` feature is really useful, but currently its type declaration ```
@types/dotenv-webpack
@7.0.7
``` does not include  `prefix`. 

Do you consider adding this property to the type declaration ?

**Comment by mrsteele** [comment]
@dbwcooper would you mind doing the PR for it?

**Comment by dbwcooper** [comment]
> @dbwcooper would you mind doing the PR for it?

@types/dotenv-webpack@7.0.8
