### ISSUE TITLE
Facing issue with accessing environment variables. My configurations are:

### ISSUE THREAD

**Issue by afsheen-a** [mrsteele/dotenv-webpack#490]
webpack.config.js:
```
plugins: [
      new DotEnv({ path: `./.env.${env.env}`, systemvars: true }),
      new CopyWebpackPlugin({
        patterns: [
          {
            from: path.resolve(__dirname, 'public'),
            to: path.resolve(__dirname, 'dist'),
          },
        ],
      }),
    ],
```

.env.local:

```API_BASE_URL=https://my-url```

index.js:

```
const BASE_URL = process.env.API_BASE_URL;
console.log(process.env) //this gives me an empty object
console.log(process.env.API_BASE_URL) //undefined
```

_Originally posted by @afsheen-a in https://github.com/mrsteele/dotenv-webpack/issues/481#issuecomment-1221824152_

**Comment by mrsteele** [comment]
If you console log "env.env" do you get "local"?

**Comment by afsheen-a** [comment]
yes, I do. Closing this issue because upon closer inspection I found that I was not assigning the env variable anywhere in the environment through the terminal and doing so resolved my problem. Thanks!

**Comment by afsheen-a** [comment]
Assigning variables through the terminal didn't resolve the issue. webpack was looking for a .env.production file to take variables from on build time. Because I was building and starting the server together, I missed it completely. Adding the file with configuration resolved my issue.
