### ISSUE TITLE
systemvars not trumping .env vars

### ISSUE THREAD

**Issue by maka-io** [mrsteele/dotenv-webpack#491]
```
“systemvars: true; //load all the predefined 'process.env' variables which will trump anything local per dotenv specs. ”

— https://www.npmjs.com/package/dotenv-webpack
```

It looks like this is not really working; the system environment variables (process.env) are not "trumping" the local .env variables.

Specifically, when using Dotenv in webpack along with `REACT_APP_` variables.

**Comment by caleb15** [comment]
It works for me with `process.env`. Maybe the bug is specific to REACT_APP_? :thinking:

**Comment by maka-io** [comment]
Sorry, should have closed this earlier 😬

The problem was actually in my CI/CD; we have a build and deploy the phase and the bundle that gets created does not know about the environment.  Only the deployment phase has the env variables, but the bundle is already created 😔.

Not a fault of this package!
