### ISSUE TITLE
How to set multiline variables？

### ISSUE THREAD

**Issue by jerry9022** [mrsteele/dotenv-webpack#494]
PUBLIC_KEY="-----BEGIN PUBLIC KEY-----
...
p3V5fdWO18j...
...
-----END PUBLIC KEY-----"

It doesn't seem to support。

**Comment by mrsteele** [comment]
Hi @jerry9022 , perhaps you didn’t read close enough but the readme actually shows an example:
https://github.com/mrsteele/dotenv-webpack#create-a-env-file

Try that out!

**Comment by yxy9022** [comment]
Sorry, my expression is wrong。

**Comment by yxy9022** [comment]
Sorry, I may have made a mistake. I originally meant "multiline values" like this:
PRIVATE_ KEY="-----BEGIN RSA PRIVATE KEY-----
...
Kh9NV...
...
-----END RSA PRIVATE KEY-----"
I read the dotenv library（ https://www.npmjs.com/package/dotenv ）Supported at 15.0.0+. The dependency dotenv you use is version 14. Maybe you need to make an upgrade。

**Comment by mrsteele** [comment]
@yxy9022 have you tried using a “\n” on a single line?

multiline, I can surely bump dotenv but of course that’s a little more involved 😊
