### ISSUE TITLE
How to use the prefix param properly?

### ISSUE THREAD

**Issue by getJv** [mrsteele/dotenv-webpack#498]
I read the README file and issue #480 I tried several combinations and I cant find a way.  Could you please help to set my configs properly?

Im using an embedded react project inside a Symfony project. so basically they share the same .env file. for this reason, my env file is something like this:

```bash
VARIABLE_NOT_FOR_REACT="some_value"
REACT_APP_VARIABLE_ONLY_FOR_REACT="some_value"
```
The issue is when I install the 'dotenv-webpack' it gave access to all .env variables to react-app. How is the setting to only give access to those that have the 'REACT_APP_' as prefix?

I already tried:

```bash
const Dotenv = require('dotenv-webpack');

// 1
.addPlugin(
        new Dotenv()
);

// 2
.addPlugin(
        new Dotenv(
            {prefix: 'REACT_APP_'}
        )
);

// 3
.addPlugin(
        new Dotenv(
           { prefix: 'process.env.REACT_APP_'}
        )
);

// 4
.addPlugin(
        new Dotenv(
            {prefix: 'import.meta.env.REACT_APP_'}
        )
);


```

- none of thos worked (2,3,4). I always got undefined when I use: `const myVar = process.env.REACT_APP_VARIABLE_ONLY_FOR_REACT;`
- for settings number 1, the value is loaded from the env as expected...
- yes, I restarted my npm server before testing each of those settings.

**Comment by Jimbolino** [comment]
This package will string replace only the variables that are being referenced in the code.

The prefix is meant to switch between the (legacy) `process.env` syntax, or the new module `import.meta.env` syntax

**Comment by mrsteele** [comment]
If you set prefix to “REACT_APP_” and had an environment variable “HOST” then your definition in code would be “REACT_APP_HOST”

the default is “process.env.” Which would make the definition “process.env.HOST”.

Ill close for now but feel free to reopen if I missed something.

**Comment by mrsteele** [comment]
Makes sense. Can you set the prefix in the Dotenv config to match the VITE one?

**Comment by Jimbolino** [comment]
I think if you set the prefix to `import.meta.env` it will be compatible with how vite handles env variables.
The main difference that vite only allows env variables that have the `VITE_*` prefix, by default.
This can be changed to something else in config, but cannot be disabled.

So with this package you cannot get the same behavior as how vite does it.
