### ISSUE TITLE
Env variables not accessible in webpack config

### ISSUE THREAD

**Issue by cosi-conda** [mrsteele/dotenv-webpack#503]
I set up the webpack config like so:

```

const DotenvWebpackPlugin = require("dotenv-webpack");
...

    plugins: [
      new DotenvWebpackPlugin({
        systemvars: true,
        path: `./env/.env.${env.NODE_ENV}`
      }),
      new HtmlWebpackPlugin({
        filename: "something.html",
        template: "./src/_template",
        SOME_VAR: process.env.SOME_VAR
      }),
      ...
     ]
    ...
```

But the process.env.SOME_VAR from my .env file is undefined in the template

**Comment by haaaafgdbar** [comment]
dotenv-webpack reads variables inside the.env file that are not available in the runtime environment, just like global variables set by DefinePlugin and EnvironmentPlugin, only available in the compilation environment. That's what I understand

**Comment by mrsteele** [comment]
If you need access to them, feel free to simply:
```javascript
require(‘dotenv-defaults’).config()
```
