### ISSUE TITLE
_dotenvwebpack.default is not a constructor

### ISSUE THREAD

**Issue by ReinGomezWP** [mrsteele/dotenv-webpack#509]
I'm getting a problem when trying to add it as one of the plugins in my webpack project generated from Nx
```
module.exports = composePlugins(withNx(), withReact(), (config) => {
  // Loaders
  config.module.rules.push({
    test: /\.(scss|css|sass)$/,
    use: [{ loader: 'postcss-loader', options: { sourceMap: true } }],
    type: 'css/auto',
  });

  config.plugins.push(new Dotenv());

  return config;
});
```

**Comment by mrsteele** [comment]
Hey @ReinGomezWP , how are you importing this library?

**Comment by ReinGomezWP** [comment]
Hi @mrsteele 
I'm importing it as so:
````
import Dotenv from 'dotenv-webpack';
````

**Comment by mrsteele** [comment]
Thanks, have you tried using this instead? You are doing it right but I'm just curious:

```js
const Dotenv = require("Dotenv-webpack")
```

**Comment by ReinGomezWP** [comment]
Yes I did, I actually even converted the file from `ts` to `js` to test.
I'm sorry I forgot to mention I was using Rspack for a bundler but according to their [website](https://rspack.dev/plugins/webpack/environment-plugin#dotenvplugin), Rspack supports dotenv-webpack

**Comment by mrsteele** [comment]
That is strange. Can you tell me anything about your specific problem? Error message, or are the env variables not working? Give me as much detail as you can so I can try and get you unstuck here.

**Comment by ReinGomezWP** [comment]
I'm really sorry but this seems like a bug in NX and not this plugin.
Let me close this ticket.
https://github.com/nrwl/nx/issues/28391

**Comment by mrsteele** [comment]
I'm actually relieved, I was having a hard time with this one
