### ISSUE TITLE
Question about a line

### ISSUE THREAD

**Issue by JiDai** [mrsteele/dotenv-webpack#51]
Hi,

I dont understand this line : 
[https://github.com/mrsteele/dotenv-webpack/blob/6c8b8ee481b73407e3e8ff8fca25ece9404e3129/src/index.js#L48](https://github.com/mrsteele/dotenv-webpack/blob/6c8b8ee481b73407e3e8ff8fca25ece9404e3129/src/index.js#L48)
Why do you test 2 same values ?

**Comment by mrsteele** [comment]
Great catch!

So looking at the history of that line, we used to do the following:
```javascript
const value = process.env[key] || this.env[key]
```
But we eventually made the `env` object ingest the `process.env` variables only if `options.systemvars` was set to true.

So you are right, we can just remove that second part in the next update.

Thanks again for the catch @JiDai!
