### ISSUE TITLE
.env clarification

### ISSUE THREAD

**Issue by TheoMer** [mrsteele/dotenv-webpack#55]
So, I've defined my Dotenv plugin as follows:

```
    new Dotenv({
      path: './.env', // Path to .env file (this is the default) 
      safe: true // load .env.example (defaults to "false" which does not use dotenv-safe) 
    })
```
and as a result need to specify both a .env and an .env.example in my root directory, the .env.example being a mirror image of .env, minus any associated values for the variables. 

Why? Why can I not just specify the .env file without the need for the .env.example?

**Comment by TheoMer** [comment]
Aha!, and to answer my own question. One reason is so that a copy of .env.example can be deployed to github, safe in the knowledge that it contains only variable definitions, and no associated values.

**Comment by mrsteele** [comment]
@TheoMer if you think that our docs could be a little more clear feel free to submit a PR.
