### ISSUE TITLE
Webpack 3.0 support

### ISSUE THREAD

**Issue by mrsteele** [mrsteele/dotenv-webpack#60]
We should check for support in webpack 3.0.

Not to mention trying to figure out how we can be backwards compatible and future-compatible and stop greenkeeper from yelling at me.

**Comment by byronmejia** [comment]
We're already up to webpack 3.0? :cry: 

Right as I legit just got back into web development.

I'll give it a casual look soon. Trying to setup a boilerplate ready for webpack 3.0

**Comment by mrsteele** [comment]
No sooner did I see they had a release candidate ready did they release it.

I'm not sure of the impact it would have on this plugin, but yeah feel free to have a look and see if there are any breaking changes.

Thanks @byronmejia and welcome back to the web-dev world!

**Comment by luiz290788** [comment]
You only need to update the peer dependency to webpack@3.0.0
I've tested using the code from this [pull request](https://github.com/mrsteele/dotenv-webpack/pull/61) and it worked perfectly.

If you give me access I can merge the pull request, test it and release the new version.

**Comment by mrsteele** [comment]
@luiz290788 I still wanna maintain compatibility with earlier versions of webpack. Any suggestions to honor both 1.x.x to 3.x.x? I think I need to do a ranged peer dependency but I haven't had time to try it out.

**Comment by luiz290788** [comment]
@mrsteele I have just tried to update webpack and it worked without any change in the package.json
I just updated it to 3.0.0, removed my node_modules and installed it again with yarn and it is working fine now.

**Comment by mrsteele** [comment]
@luiz290788 thanks for that, any ideas though on how to maintain backwards compatibility?

**Comment by luiz290788** [comment]
@mrsteele I have tested with my application using webpack 2 and webpack 3. I could make it work with the version 3.0.0 after deleting my node_modules and reinstalling it again. I think it is already backwards compatible.

**Comment by mrsteele** [comment]
@luiz290788 what would you recommend with the peerDependency property in package.json?

**Comment by luiz290788** [comment]
@mrsteele I might be wrong but I think we don't need to change it. Because it specifies that we need version bigger than 1.14.0 so it will work with 2.x.x and 3.x.x

**Comment by mrsteele** [comment]
I just merged the PR by greenkeeper. Should still be backwards compatible but anyone who has problems please let me know if anything comes up.
