### ISSUE TITLE
'Missing environment variable: ' when variable is defined as system variable but not .env file

### ISSUE THREAD

**Issue by JordanBelford** [mrsteele/dotenv-webpack#62]
Obviously this assumes systemvars is enabled.

Looking through the code, 
'env' contains variables from .env
'vars' contains variables from process.env

The 'Missing environment variable' error is thrown if any value from the blueprint is not in 'env'.
I believe it should also check for the key in 'vars'

Sounds like a very simple fix. Do I understand this correctly?

**Comment by mrsteele** [comment]
First we populate `vars` if `options.systemvars` is true.

`env` is loaded and if `options.safe` is set we use the `dotenv-safe` config (to verify you populate all required env vars).

Are you suggesting the systemvars should take precedence over the local env?

**Comment by mrsteele** [comment]
(I have a background in CSS so I like to think that the local env vars should overwrite the systemvars to allow differential environments).

**Comment by JordanBelford** [comment]
I agree that the .env file should override any systemvars. If a var is marked as required in the example file, safe mode should pass as long as the car is defined in either .env or as a system var. But if it's defined in both, then use the one in .env.

The use case for this is CI environments when there is no .env file, but all required vars are defined as system variables. 

Example:
Dotenv config
```{
      path: './.env',
      safe: true,
      systemvars: true
    }```

.env.example
TEST=
TEST2=

.env
TEST=1

systemvars
TEST2=2
(plus others)

This currently throws the Missing Variable error.

**Comment by mrsteele** [comment]
Hmmm, I see what you are saying now: System variables should satisfy the environment variable requirement.

Anyone else have some opinions about this?

**Comment by mrsteele** [comment]
@JordanBelford just wanted to mention that I have a child due any minute, so I personally will not be able to get around to this as quickly as I normally would. As a slight work-around you can simply remove that var from env-safe if you need your fix out quick.

I also wanna hear what others have to say with this gap on my end. My initial thoughts are to take your suggestion, as it seems to be what `dotenv-safe` is doing here: https://github.com/rolodato/dotenv-safe/blob/master/index.js#L34

**Comment by JordanBelford** [comment]
@mrsteele Best of luck with your child! 

The solution I am going with is to use dotenv-safe for variable validation, since it recognizes system variables. 

I am using dotenv-webpack with safe mode disabled and systemvars enabled.

This way each package has a single responsibility.

**Comment by mrsteele** [comment]
Thanks. I'm killing time at the hospital now.

I think I agree with you and I made a PR that shows the approach #63.

Let me know what you think of that and if that properly addresses. I can pull that in and CI will auto release with semantic release so it won't be hard to add.

**Comment by sessio** [comment]
👍 for this, came looking for answers to the same issue.
The PR looks good, really helpful stuff when dealing with CI's but keeping dev env locally in a file.
..and congrats on the new personal fork, if that happened by now 👶 :)
