### ISSUE TITLE
Does not work with webpack-dev-server

### ISSUE THREAD

**Issue by screendriver** [mrsteele/dotenv-webpack#78]
Hi,

it seems that `dotenv-webpack` does not work with `webpack-dev-server`. In my normal builds without `webpack-dev-server` I can see that the env variables are replaced as expected. But when I use `webpack-dev-server` all my env variables are `undefined`.

webpack: 3.5.5
webpack-dev-server: 2.7.1
dotenv-webpack: 1.5.4

**Comment by jbailey** [comment]
Any good ways around this?  Seeing the same thing.

**Comment by mrsteele** [comment]
Hey @screendriver (and @jbailey), sorry somehow this issue slipped through the cracks.

Just to jump-start me to get this resolved quickly, do you have a repo in progress/PR that I can look at to know more about your configuration?

**Comment by mrsteele** [comment]
I use my `dotenv-webpack-example` library to test out some of these issues and I just made a commit to it that has a working example with `webpack-dev-server`. 

Feel free to have a look.

https://github.com/mrsteele/dotenv-webpack-example

Of course, this is a minimally configured approach so it may or may not help you out. Since it can work I imagine you may have something else going on and conflicting with your variables. Since it has occurred more than once it may be a common problem but I am more than happy to investigate.

**Comment by jbailey** [comment]
Hmm, my webpack config looks the same, i just dont get the env variables from the file.  I've tried in two different projects.  I'm using webpack 2.2.1 for what it's worth.

**Comment by mrsteele** [comment]
I went ahead and upgraded everything and it still works. Do you have any other plugins that may be conflicting (historically that is what it ends up being).

```
$ npm ls --depth=0
├── babel-core@6.26.0
├── babel-loader@7.1.2
├── babel-preset-es2015@6.24.1
├── dotenv-webpack@1.5.4
├── webpack@3.5.6
└── webpack-dev-server@2.7.1
```

**Comment by screendriver** [comment]
I don't know how or what changed but in the meantime it's working on my machine 😳 🤔

**Comment by mrsteele** [comment]
Adding the `help wanted` label and maybe others can contribute if they have any problems as well.

**Comment by denizdogan** [comment]
For what it's worth, I use webpack-dev-server with dotenv-webpack without any issues.

**Comment by mrsteele** [comment]
Haha from where I’m sitting @denizdogan it’s worth a lot!

**Comment by nickbouldien** [comment]
I just installed dotenv-webpack, and initially had the same issue as screendriver (OP), with it showing all the .env vars as undefined, but after killing the server a few times and rebuilding/restarting, it worked 

I know that doesn't help on this, just thought it was interesting

**Comment by cbovis** [comment]
Can confirm I'm also not seeing any issues using dotenv-webpack with webpack-dev-server. Worked first time.

webpack: 3.11.0
webpack-dev-server: 2.11.1
dotenv-webpack: 1.5.5

**Comment by mrsteele** [comment]
Thanks @cbovis I'm going to assume this is resolved at this point but @screendriver if you think this is still a problem feel free to reopen.

**Comment by screendriver** [comment]
Hi @mrsteele,

on my machine it works again. I don't know why but the main thing is it works 😁 So it's ok for me to close the issue 😉

**Comment by blainehansen** [comment]
I think I've figured out what's happening here. It has to do with the overwrite behavior of `dotenv`

**Comment by evenfrost** [comment]
In case anyone stumbles upon a similar issue, make sure you're not destructuring `process.env` as it [doesn't currently work](https://github.com/mrsteele/dotenv-webpack/issues/70). Instead, use full notation when referring to environment vars, e.g. `process.env.YOUR_ENV_VAR`.
