### ISSUE TITLE
Expanding env vars?

### ISSUE THREAD

**Issue by FDiskas** [mrsteele/dotenv-webpack#80]
Is it possible to expand variables? I see you are using dotenv dependency
https://github.com/motdotla/dotenv-expand/blob/master/test/.env
https://www.npmjs.com/package/dotenv#can-i-customizewrite-plugins-for-dotenv

**Comment by mrsteele** [comment]
I don't see why not, but at the same time this is an issue I have realized a while back where we need to support multiple dotenv features aside from dotenv at its core.

Currently I have `dotenv` and `dotenv-safe` methodologies, however I recognize there are a lot of others out there (as you have mentioned another).

If you can think of a way to support this, a PR is always welcome!

**Comment by mrsteele** [comment]
Closing this and keeping the conversation going in #98
