### ISSUE TITLE
Support export in .env file

### ISSUE THREAD

**Issue by agarrharr** [mrsteele/dotenv-webpack#90]
Some `.env` files have lines like this, so that you can source the file in bash:

```
export S3_BUCKET=YOURS3BUCKET
export SECRET_KEY=YOURSECRETKEYGOESHERE
```

Here is some documentation from dotenv, which is a ruby gem: https://github.com/bkeepers/dotenv#usage

dotenv-webpack doesn't load in those env variables if it has an export in front of it. It would be nice if it supported this format.

**Comment by mrsteele** [comment]
Thanks for the suggestion @agarrharr, I don't suppose you would be interested in making a PR for this?

**Comment by mrsteele** [comment]
Rereading this I think its a misconception that this is a ruby implementation.

We follow the js implementation of dotenv which can be found here: https://github.com/motdotla/dotenv

I'm closing this for now but feel free to reopen.

**Comment by agarrharr** [comment]
I see. That's fine. If you look at https://github.com/motdotla/dotenv/issues/213, it talks about this, and they decided not to add this feature.

**Comment by metaskills** [comment]
Using this now https://github.com/sneakertack/nvar
