### ISSUE TITLE
how can i reload the env?

### ISSUE THREAD

**Issue by lluvio** [mrsteele/dotenv-webpack#92]

**Comment by mrsteele** [comment]
Hey @lluvio!

Perhaps some more context is needed but here is what I think you are asking:

**How do I rebundle my env variables?**

This would require you use something like an `npm run dev` script to make sure that your scripts are watching for files to change, and when they change the bundle process fires off. You can find plenty of those in boilerplate webpack projects.

Let me know if that isn't the proper context and what you were reall trying to ask.

**Comment by mrsteele** [comment]
Closing due to lack of participation.

Feel free to reopen this if you can provide more details, thanks.
