### ISSUE TITLE
Support dotenv-expand?

### ISSUE THREAD

**Issue by mrsteele** [mrsteele/dotenv-webpack#98]
This was brought up a while back in #80 and I wanna bring it up here.

I was doing more research about what `dotenv-expand` was and found that it could be a feature to simply offer the ability to expand variables using vs the regular `dotenv` since it appears to me that they could coexist alongside one another.

https://github.com/motdotla/dotenv-expand/blob/master/test/.env

I'm curious what other's thoughts are, especially if there are security concerns to be worried about.

**Comment by mrsteele** [comment]
Added a commit which solves this problem, but still unsure if I wanna support that...

**Comment by SavePointSam** [comment]
I would really like this feature. Until then, I cannot use this package. :(

**Comment by wilsson** [comment]
will they come to support this feature?

**Comment by mrsteele** [comment]
Here is my PR that has been pending for a while... 

https://github.com/motdotla/dotenv-expand/pull/16

I wanna support this feature, while also not copy-pasting the approach from that repo. It would be best if I could just hook into it but we will see what the author says...
