### ISSUE TITLE
Support typescript

### ISSUE THREAD

**Issue by FDiskas** [mrsteele/dotenv-webpack#99]
There is missing type definitions :(

**Comment by mrsteele** [comment]
@FDiskas I would be lying if I said I could resolve this issue easily.

Would you mind maybe taking a stab at it and submit a PR?

**Comment by FDiskas** [comment]
Write your plugin with type script and it will generate definitions.
You can use https://github.com/nfq-eta/react-router4-with-layouts as boiler plate
